spring:
    application:
        name: gate-demo-client

server:
    port: 8764

eureka:
    instance:
        statusPageUrlPath: ${management.context-path}/info
        healthCheckUrlPath: ${management.context-path}/health
        preferIpAddress: true
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

gate:
    client:
        authHeader: access-token
        authHost: http://localhost:8762/api/authen