spring:
    application:
        name: gate-eureka

server:
    port: 8761 #启动端口

eureka:
    client:
        registerWithEureka: false  #false:不作为一个客户端注册到注册中心
        fetchRegistry: false
    server:
      enable-self-preservation: false #自我保护，为true时，可以启动，但报异常：Cannot execute request on any known server
      eviction-interval-timer-in-ms: 5000 # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
