logging:
    level:
#        tk.mybatis: DEBUG
        com.github.cc.gate: INFO
  #  config: classpath:logback.xml
    # path: /ag/admin
spring:
    application:
        name: gate-way
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    datasource:
        name: test
        url: jdbc:mysql://172.17.24.99:3306/ag_gate_way?useUnicode=true&characterEncoding=UTF8
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
    basepackage: com.github.cc.gate.gateway.mapper
    xmlLocation: classpath:mapper/**/*.xml

server:
    port: 8762
