logging:
    level:
        tk.mybatis: DEBUG
        com.github.cc.gate: INFO
  #  config: classpath:logback.xml
    # path: /ag/admin
spring:
    application:
        name: gate-way
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    datasource:
        name: test
        url: jdbc:mysql://172.17.24.99:3306/ag_gate_way?useUnicode=true&characterEncoding=UTF8
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    cloud:
      loadbalancer:
        retry:
          enabled: true

mybatis:
    basepackage: com.github.cc.gate.gateway.mapper
    xmlLocation: classpath:mapper/**/*.xml

server:
    port: 8762

gate:
    ignore:
        startWith: /admin,/index,/about
        contain: .
    client:
        authHeader: access-token
        authHost: http://localhost:8762/api/authen
    api:
        secret: mySecret   #jwt 加密密钥
        expiration: 7200  # 过期秒数
        authHeader: access-token

eureka:
    instance:
        statusPageUrlPath: ${management.context-path}/info
        healthCheckUrlPath: ${management.context-path}/health
        preferIpAddress: true
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

zuul:
    prefix: /api #为zuul设置一个公共的前缀
    semaphore:
        max-semaphores: 1000
    host:
        max-total-connections: 500

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

management:
  security:
    enabled: false

swagger:
    basepackage: com.github.cc.gate.gateway.controller.api
    service:
        name: 网关中心Api
        description: 网关中心鉴权Api
        developer: Frank